### PR TITLE
[keycloak] support for topologySpreadConstraints

### PR DESCRIPTION
**Pull request by raffis**
Adds support to define a templated topologySpreadConstraints field.

### CODE REVIEW

**Comment by raffis** [comment]
@mircohaug @thomasdarimont can we merge this?

**Comment by thomasdarimont** [comment]
@raffis Thanks for your contribution! Would you mind rebasing this again?

**Comment by raffis** [comment]
> @raffis Thanks for your contribution! Would you mind rebasing this again?

👍🏻 @thomasdarimont

**Comment by thomasdarimont** [comment]
@raffis thanks for the update! Please squash your commits and prefix the commit message with `[keycloak] `

**Comment by raffis** [comment]
> @raffis thanks for the update! Please squash your commits and prefix the commit message with `[keycloak] `

done

**Comment by thomasdarimont** [comment]
@raffis forgot to add, could you mention this ticket in the commit message? `Fixes #463`.

**Comment by raffis** [comment]
> @raffis forgot to add, could you mention this ticket in the commit message? `Fixes #463`.

Didn't see that there is a ticket for this 🙈 , ok done.

**Review by thomasdarimont — APPROVED** [review]
LGTM

**Pull request merged**
