### PR TITLE
[keycloak] Allow ingress apiVersion to be specified directly in values.yaml instead of using Capabilities.

### PR DESCRIPTION
**Pull request by juliohm1978**
Fix https://github.com/codecentric/helm-charts/issues/496

Signed-off-by: juliohm1978 <jhm@juliohm.com.br>

### CODE REVIEW

**Comment by lesmyrmidons** [comment]
+1

**Comment by olevitt** [comment]
Shouldn't the check here : https://github.com/codecentric/helm-charts/blob/f7914e5bb63ad63264fe024cbf735b5faf7d9320/charts/keycloak/templates/ingress.yaml#L95

be adapted to use the value overriden instead of re-checking using capabilities ? The apiVersion used need to be consistent otherwise we risk having an invalid syntax

**Comment by SeWieland** [comment]
Please have a look at #501 / #502 as an alternative

**Comment by juliohm1978** [comment]
Thanks! I think either one would work. But I confess there is an argument for usability, not requiring chart users to be aware of api versions used under the hood.

I'm all for approving #501 and #502, if that's the more popular choice :)

**Comment by mircohaug** [comment]
Hi thanks for the PR but I prefer the usability of https://github.com/codecentric/helm-charts/pull/501

**Pull request closed without merging**
