### PR TITLE
[keycloakx] Bump Keycloak to v21.1.1

### PR DESCRIPTION
**Pull request by Footur**
Keep the [upgrading guide](https://www.keycloak.org/docs/21.1.1/upgrading/index.html) in mind.

### CODE REVIEW

**Review by justmike1 — APPROVED** [review]
Tested, no breaking changes. LGTM

**Comment by Tim-Schwalbe** [comment]
Also tested, no problems.

**Comment by trietsch** [comment]
Any updates on when this will be merged? :)

**Comment by scila1996** [comment]
Please merge this PR 🥹

**Pull request merged**
