### PR TITLE
[keycloak] Create new major chart release

### PR DESCRIPTION
**Pull request by unguiculus**
This PR collects a number of changes for a new major chart release.

- [x] Use nindent and improve indentation
- [x] Use new support for running scripts at startup
- [x] Upgrade Keycloak to 6.0.1
- [x] Make actionTokens cache configurable
- [x] Upgrade Postgresql dependency
- [x] Update labels to use new Kubernetes label conventions
- [x] Improve documentation on CLI handling
- [x] Add flag for toggling CLI execution globally
- [x] Use password file for admin user
- [x] Add upgrading section to README

Fixes: #28 
Fixes: #44 
Fixes: #45

### CODE REVIEW

**Comment by dojadop** [comment]
Hi @unguiculus Keycloak recently added `/health` and `/metrics` endpoints in their 6.0.0 release: https://www.keycloak.org/docs/latest/release_notes/index.html#smallrye-health-and-metrics-extensions

What are your thoughts on updating the ready and/or liveliness probe to take advantage of the new /health endpoint exposed by Wildfly? I can open a PR against this one if you would like.

**Comment by unguiculus** [comment]
@dojadop That's for the suggestion. Please create PR.

**Comment by dojadop** [comment]
After making the changes I do not know if the health endpoint is ready for prime time.  After about 3 minutes of running it fails with a statuscode of 404. 

Additionally, you have to expose the wildfly management port inside the Kubernetes cluster since the health check port (9990) is bound to only 127.0.0.1.

I pushed up my changes here: https://github.com/dojadop/helm-charts/tree/useHealthEndpoint

**Comment by davidholsgrove** [comment]
Hi @unguiculus,

I've been using your `next-major` branch as I was looking forward to using the startupScripts capability added by JBoss in their entrypoint.

I wasn't seeing the specified startup script run after the `keycloak.cli` though (after confirming the configmap was correctly placing the scripts in `/opt/jboss/startup-scripts`)

I traced through, and see that the keycloak container's command is `/scripts/keycloak.sh` which comes from `configmap-sh.yaml`. It looks like we're doubling up the running of `keycloak.cli` both in `/scripts/keycloak.sh` *and* the `docker-entrypoint.sh` -> `autorun.sh`;
https://github.com/jboss-dockerfiles/keycloak/blob/master/server/tools/docker-entrypoint.sh#L177
https://github.com/jboss-dockerfiles/keycloak/blob/master/server/tools/autorun.sh#L11

I made the following change to `configmap-sh.yaml` (leaving your `configmap-startup.yaml` as is) and I was able to see my startupScripts executed;

```diff
From b4fdefcc918c8f6a5208d4ebe9b87a186c3058f4 Mon Sep 17 00:00:00 2001
From: David Holsgrove <david.holsgrove@biarri.com>
Date: Tue, 18 Jun 2019 15:55:32 +1000
Subject: [PATCH 1/2] [keycloak] JBoss docker-entrypoint.sh includes autorun.sh
 which will already run keycloak.cli from startupscripts.

Remove this duplication, which seemed to be blocking on autorun.sh executing the next set of startup scripts.
---
 charts/keycloak/templates/configmap-sh.yaml | 37 ---------------------
 1 file changed, 37 deletions(-)

diff --git a/charts/keycloak/templates/configmap-sh.yaml b/charts/keycloak/templates/configmap-sh.yaml
index 4fcbeca..db8bb21 100644
--- a/charts/keycloak/templates/configmap-sh.yaml
+++ b/charts/keycloak/templates/configmap-sh.yaml
@@ -14,42 +14,5 @@ data:
 
     set -eu
 
-    /opt/jboss/keycloak/bin/jboss-cli.sh --file=/scripts/keycloak.cli
-
     exec /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 {{ .Values.keycloak.extraArgs }}{{- if $highAvailability }} -c standalone-ha.xml{{ else }} -c standalone.xml{{ end }}
     exit "$?"
-
-  keycloak.cli: |
-    embed-server {{- if $highAvailability }} --server-config=standalone-ha.xml{{ end }} --std-out=echo
-    batch
-
-  {{- if ne .Values.keycloak.basepath "auth" }}
-    # Changes the base path to be /keycloak.basepath instead of /auth
-    /subsystem=keycloak-server:write-attribute(name=web-context,value={{ if eq .Values.keycloak.basepath "" }}ROOT{{ else }}{{ .Values.keycloak.basepath }}{{ end }})
-    {{- if eq .Values.keycloak.basepath "" }}
-    /subsystem=undertow/server=default-server/host=default-host:write-attribute(name=default-web-module,value=keycloak-server.war)
-    {{- end }}
-  {{ end }}
-
-  {{- with .Values.keycloak.cli }}
-
-    {{- tpl .nodeIdentifier $ | nindent 4 }}
-
-    {{- tpl .logging $ | nindent 4 }}
-
-    {{- tpl .reverseProxy $ | nindent 4 }}
-
-    {{- tpl .datasource $ | nindent 4 }}
-
-    {{- if $highAvailability }}
-      {{- tpl .ha $ | nindent 4 }}
-    {{- end }}
-
-    {{- with .custom }}
-      {{- tpl . $ | nindent 4 }}
-    {{- end }}
-
-  {{- end }}
-
-    run-batch
-    stop-embedded-server
-- 
2.17.1
```

When do you think we can get this PR rebased and merged to master? I've a followup PR I'm going to be submitting shortly which requires this capability 👍

**Comment by unguiculus** [comment]
@dojadop @davidholsgrove Thanks for your feedback!😀 Please note that this is only a draft PR which needs further works. I just didn't have time to continue with it. I'll have a look at your suggestions and will try and improve the PR based on those.

**Comment by unguiculus** [comment]
@dojadop I tried to find out more on the new health extension. It seems it only reports whether Keycloak itself is up and running. It doesn't tell you anything about the database. So, it's only suitable for a liveness probe, not for a readiness probe. I'd rather wait till this feature is documented before we use it.

See https://github.com/keycloak/keycloak/pull/5927

**Comment by thomasdarimont** [comment]
lgtm @unguiculus

**Comment by mxandeco** [comment]
Hi @unguiculus is it safe to start a new keycloak setup with this branch? do you expect some big breaking changes to be made on this branch? Any plan to get this released soon? Thanks.

**Comment by unguiculus** [comment]
@mxandeco I'm planning to merge this soon. Note that this branch does contain breaking changes.

**Comment by thomasdarimont** [comment]
lgtm @unguiculus thanks for the great work!

**Pull request merged**
