### PR TITLE
[mailhog] Add ability to set Web UI path

### PR DESCRIPTION
**Pull request by bkondek**
Added ability to setup custom Web UI path, which will allow
to use application in context another than "/" in ingress

Signed-off-by: Bartosz Kondek <b.kondek@piwik.pro>

### CODE REVIEW

**Comment by bkondek** [comment]
@unguiculus could you please look that this PR?
I really need that variable to use this chart with ingress

**Comment by glothriel** [comment]
@mrsegen @unguiculus Sorry guys for pinging again, but it's quite important for as, we would really like to merge this.

**Comment by unguiculus** [comment]
Sorry for the delayed response. The chart already supports adding additional environment variables.

**Comment by glothriel** [comment]
Indeed, there is `extraEnv` variable. Imo we can close this, @bkondek ?

**Comment by bkondek** [comment]
Ok, thanks, i've missed this.
In this case - closing this PR

**Pull request closed without merging**
