### PR TITLE
[keycloak] update Keycloak to 16.0.0

### PR DESCRIPTION
**Pull request by trietsch**
Also includes the security fix for Keycloak 15.1.1 as stated on https://twitter.com/keycloak/status/1471815630655528968?t=bcUUDb7E2jTEJFlvW11E8Q

### CODE REVIEW

**Comment by trietsch** [comment]
@mircohaug @thomasdarimont not sure why the test chart fails. The selenium response doesn't state the error:
```
Creating PhantomJS driver...
Opening Keycloak...
Entering username...
Entering password...
Clicking login button...
Traceback (most recent call last):
  File "/tests/test.py", line 32, in <module>
    WebDriverWait(driver, 30).until(lambda driver: '/auth/admin/master/console/' in driver.current_url)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by thomasdarimont** [comment]
@trietsch thanks for your PR, but we'd rather not use a just released .0 version with incompatible changes (wildfly 25 upgrade) 
for the helm chart for now.  Instead we'll update the chart to use Keycloak version 15.1.1.

**Comment by trietsch** [comment]
@thomasdarimont alright, understandable. Though, is it possible to release two versions then? One for 15.1.1 and one for 16.0.0? For those willing to upgrade to 16.0.0, have the option to upgrade.

**Comment by grafjo** [comment]
the 16.1.0 version was released today aswell - see https://www.keycloak.org/2021/12/keycloak-1610-released.html

**Comment by mxandeco** [comment]
> @trietsch thanks for your PR, but we'd rather not use a just released .0 version with incompatible changes (wildfly 25 upgrade) for the helm chart for now. Instead we'll update the chart to use Keycloak version 15.1.1.

Is there an eta for the chart with `15.1.1` ?

**Comment by thomasdarimont** [comment]
Thanks for your PR we updated the Keycloak version via https://github.com/codecentric/helm-charts/pull/532

**Pull request closed without merging**
